=== phpmd/phpmd/public/resources/web/xml/ruleset_xml_schema_1.0.0.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="https://phpmd.org/xml/ruleset/1.0.0"
        targetNamespace="https://phpmd.org/xml/ruleset/1.0.0"
        elementFormDefault="qualified">

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="format" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache-strategy" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="baseline-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="bootstrap" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="minimum-priority" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="maximum-priority" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="threads" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="paths" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="exclude-pattern" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="include-pattern" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="suffixes" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="php-includepath" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="php-includepath" type="xs:string">
    </xs:element>

    <xs:element name="description" type="xs:string">
    </xs:element>

    <xs:element name="include-pattern" type="xs:string">
    </xs:element>

    <xs:element name="exclude-pattern" type="xs:string">
    </xs:element>

    <xs:element name="rule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="priority" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:ID" use="optional"/>
            <xs:attribute name="file" type="xs:string" use="optional"/>
            <xs:attribute name="since" type="xs:string" use="optional"/>
            <xs:attribute name="ref" type="xs:string" use="optional"/>
            <xs:attribute name="message" type="xs:string" use="optional"/>
            <xs:attribute name="externalInfoUrl" type="xs:string" use="optional"/>
            <xs:attribute name="class" type="xs:NMTOKEN" use="optional"/>
            <xs:attribute name="dfa" type="xs:boolean" use="optional"/>  <!-- rule uses dataflow analysis -->
            <xs:attribute name="typeResolution" type="xs:boolean" default="false" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="example" type="xs:string"/>

    <!-- Default priority is the lowest -->
    <xs:element name="priority" type="xs:int" default="5"/>

    <xs:element name="properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="value" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
            <xs:attribute name="pluginname" type="xs:NMTOKEN" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="value" type="xs:string">
    </xs:element>

    <xs:element name="exclude">
        <xs:complexType>
            <xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== phpmd/phpmd/rulesets/design.xml
<?xml version="1.0"?>

<ruleset name="Design Rules"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>
The Design Ruleset contains a collection of rules that find software design related problems.
    </description>

    <rule name="ExitExpression"
          since="0.2"
          message = "The {0} {1}() contains an exit expression."
          class="PHPMD\Rule\Design\ExitExpression"
          externalInfoUrl="https://phpmd.org/rules/design.html#exitexpression">
        <description>
            <![CDATA[
An exit-expression within regular code is untestable and therefore it should
be avoided. Consider to move the exit-expression into some kind of startup
script where an error/exception code is returned to the calling environment.
            ]]>
        </description>
        <priority>1</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {
    public function bar($param)  {
        if ($param === 42) {
            exit(23);
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="EvalExpression"
          since="0.2"
          message = "The {0} {1}() contains an eval expression."
          class="PHPMD\Rule\Design\EvalExpression"
          externalInfoUrl="https://phpmd.org/rules/design.html#evalexpression">
        <description>
            <![CDATA[
An eval-expression is untestable, a security risk and bad practice. Therefore
it should be avoided. Consider to replace the eval-expression with regular
code.
            ]]>
        </description>
        <priority>1</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {
    public function bar($param)  {
        if ($param === 42) {
            eval('$param = 23;');
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="GotoStatement"
          since="1.1.0"
          message="The {0} {1}() utilizes a goto statement."
          class="PHPMD\Rule\Design\GotoStatement"
          externalInfoUrl="https://phpmd.org/rules/design.html#gotostatement">
        <description>
            <![CDATA[
Goto makes code harder to read and it is nearly impossible to understand the
control flow of an application that uses this language construct. Therefore it
should be avoided. Consider to replace Goto with regular control structures and
separate methods/function, which are easier to read.
            ]]>
        </description>
        <priority>1</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {
    public function bar($param)  {
        A:
        if ($param === 42) {
            goto X;
        }
        Y:
        if (time() % 42 === 23) {
            goto Z;
        }
        X:
        if (time() % 23 === 42) {
            goto Y;
        }
        Z:
        return 42;
    }
}
            ]]>
        </example>
    </rule>

    <rule name="NumberOfChildren"
          since="0.2"
          message = "The {0} {1} has {2} children. Consider to rebalance this class hierarchy to keep number of children at {3} or less."
          class="PHPMD\Rule\Design\NumberOfChildren"
          externalInfoUrl="https://phpmd.org/rules/design.html#numberofchildren">
        <description>
            <![CDATA[
A class with an excessive number of children is an indicator for an unbalanced
class hierarchy. You should consider to refactor this class hierarchy.
            ]]>
        </description>
        <priority>2</priority>
        <properties>
            <property name="maximum" value="15" description="Maximum number of acceptable child classes." />
        </properties>
        <example />
    </rule>

    <rule name="DepthOfInheritance"
          since="0.2"
          message = "The {0} {1} has {2} parents. Consider to reduce the depth of this class hierarchy to {3} or less."
          class="PHPMD\Rule\Design\DepthOfInheritance"
          externalInfoUrl="https://phpmd.org/rules/design.html#depthofinheritance">
        <description>
            <![CDATA[
A class with many parents is an indicator for an unbalanced and wrong class
hierarchy. You should consider to refactor this class hierarchy.
            ]]>
        </description>
        <priority>2</priority>
        <properties>
            <property name="maximum" value="6" description="Maximum number of acceptable parent classes." />
        </properties>
        <example />
    </rule>

    <rule name="CouplingBetweenObjects"
          since="1.1.0"
          message="The class {0} has a coupling between objects value of {1}. Consider to reduce the number of dependencies to {2} or less."
          class="PHPMD\Rule\Design\CouplingBetweenObjects"
          externalInfoUrl="https://phpmd.org/rules/design.html#couplingbetweenobjects">
        <description>
            <![CDATA[
A class with too many dependencies has negative impacts on several quality
aspects of a class. This includes quality criteria like stability,
maintainability and understandability
            ]]>
        </description>
        <priority>2</priority>
        <properties>
            <property name="maximum" value="13" description="Maximum number of acceptable dependencies." />
        </properties>
        <example>
            <![CDATA[
class Foo {
    /**
     * @var \foo\bar\X
     */
    private $x = null;

    /**
     * @var \foo\bar\Y
     */
    private $y = null;

    /**
     * @var \foo\bar\Z
     */
    private $z = null;

    public function setFoo(\Foo $foo) {}
    public function setBar(\Bar $bar) {}
    public function setBaz(\Baz $baz) {}

    /**
     * @return \SplObjectStorage
     * @throws \OutOfRangeException
     * @throws \InvalidArgumentException
     * @throws \ErrorException
     */
    public function process(\Iterator $it) {}

    // ...
}
            ]]>
        </example>
    </rule>

    <rule name="DevelopmentCodeFragment"
          since="2.3.0"
          message="The {0} {1}() calls the typical debug function {2}() which is mostly only used during development."
          class="PHPMD\Rule\Design\DevelopmentCodeFragment"
          externalInfoUrl="https://phpmd.org/rules/design.html#developmentcodefragment">
        <description>
            <![CDATA[
Functions like var_dump(), print_r() etc. are normally only used during development
and therefore such calls in production code are a good indicator that they were
just forgotten.
            ]]>
        </description>
        <priority>2</priority>
        <properties>
            <property name="unwanted-functions" value="var_dump,print_r,debug_zval_dump,debug_print_backtrace" description="Comma separated list of suspect function images." />
            <property name="ignore-namespaces" value="false" description="Ignore namespaces when looking for dev. fragments" />
        </properties>
        <example>
            <![CDATA[
class SuspectCode {

    public function doSomething(array $items)
    {
        foreach ($items as $i => $item) {
            // …

            if ('qafoo' == $item) var_dump($i);

            // …
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="EmptyCatchBlock"
          since="2.7.0"
          message="Avoid using empty try-catch blocks in {0}."
          class="PHPMD\Rule\Design\EmptyCatchBlock"
          externalInfoUrl="https://phpmd.org/rules/design.html#emptycatchblock">
        <description>
            <![CDATA[
Usually empty try-catch is a bad idea because you are silently swallowing an error condition
and then continuing execution. Occasionally this may be the right thing to do, but often
it's a sign that a developer saw an exception, didn't know what to do about it,
and so used an empty catch to silence the problem.
            ]]>
        </description>
        <priority>2</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {

  public function bar()
  {
      try {
          // ...
      } catch (Exception $e) {} // empty catch block
  }
}
            ]]>
        </example>
    </rule>

    <rule name="CountInLoopExpression"
          since="2.7.0"
          message="Avoid using {0}() function in {1} loops."
          class="PHPMD\Rule\Design\CountInLoopExpression"
          externalInfoUrl="https://phpmd.org/rules/design.html#countinloopexpression">
        <description>
            <![CDATA[
Using count/sizeof in loops expressions is considered bad practice and is a potential source of
many bugs, especially when the loop manipulates an array, as count happens on each iteration.
            ]]>
        </description>
        <priority>2</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {

  public function bar()
  {
    $array = array();

    for ($i = 0; count($array); $i++) {
      // ...
    }
  }
}
            ]]>
        </example>
    </rule>
</ruleset>

=== phpmd/phpmd/tests/resources/files/rulesets/exclude-pattern.xml
<?xml version="1.0" encoding="UTF-8"?>

<ruleset name="First Test RuleSet"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>Test exclude-pattern</description>
    <rule ref="rulesets/codesize.xml/CyclomaticComplexity" />
    <rule ref="rulesets/codesize.xml/NPathComplexity">
        <properties>
            <property name="maximum" value="50" />
        </properties>
    </rule>

    <!-- unix path -->
    <exclude-pattern>*sourceExcluded/*.php</exclude-pattern>
    <!-- windows path -->
    <exclude-pattern>*sourceExcluded\*.php</exclude-pattern>
</ruleset>

=== phpmd/phpmd/rulesets/unusedcode.xml
<?xml version="1.0"?>

<ruleset name="Unused Code Rules"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">
    <description>
The Unused Code Ruleset contains a collection of rules that find unused code.
    </description>

    <rule name="UnusedPrivateField"
          since="0.2"
          message="Avoid unused private fields such as '{0}'."
          class="PHPMD\Rule\UnusedPrivateField"
          externalInfoUrl="https://phpmd.org/rules/unusedcode.html#unusedprivatefield">
        <description>
Detects when a private field is declared and/or assigned a value, but not used.
        </description>
        <priority>3</priority>
        <properties>
            <property
                    name="exceptions"
                    description="Comma-separated list of field names that are allowed to be unused."
                    value="" />
        </properties>
        <example>
<![CDATA[
class Something
{
    private static $FOO = 2; // Unused
    private $i = 5; // Unused
    private $j = 6;
    public function addOne()
    {
        return $this->j++;
    }
}
]]>
        </example>
    </rule>

    <rule name="UnusedLocalVariable"
          since="0.2"
          message="Avoid unused local variables such as '{0}'."
          class="PHPMD\Rule\UnusedLocalVariable"
          externalInfoUrl="https://phpmd.org/rules/unusedcode.html#unusedlocalvariable">
        <description>
Detects when a local variable is declared and/or assigned, but not used.
        </description>
        <priority>3</priority>
        <properties>
            <property
                    name="allow-unused-foreach-variables"
                    description="Allow unused variables in foreach language constructs."
                    value="false" />
            <property name="exceptions" description="Comma-separated list of exceptions" value=""/>
        </properties>
        <example>
<![CDATA[
class Foo {
    public function doSomething()
    {
        $i = 5; // Unused
    }
}
]]>
        </example>
    </rule>

    <rule name="UnusedPrivateMethod"
          since="0.2"
          message="Avoid unused private methods such as '{0}'."
          class="PHPMD\Rule\UnusedPrivateMethod"
          externalInfoUrl="https://phpmd.org/rules/unusedcode.html#unusedprivatemethod">
        <description>
Unused Private Method detects when a private method is declared but is unused.
        </description>
        <priority>3</priority>
        <example>
<![CDATA[
class Something
{
    private function foo() {} // unused
}
]]>
        </example>
    </rule>

    <rule name="UnusedFormalParameter"
          since="0.2"
          message="Avoid unused parameters such as '{0}'."
          class="PHPMD\Rule\UnusedFormalParameter"
          externalInfoUrl="https://phpmd.org/rules/unusedcode.html#unusedformalparameter">
        <description>
Avoid passing parameters to methods or constructors and then not using those parameters.
        </description>
        <priority>3</priority>
        <properties>
            <property name="exceptions" description="Comma-separated list of exceptions" value=""/>
        </properties>
        <example>
<![CDATA[
class Foo
{
    private function bar($howdy)
    {
        // $howdy is not used
    }
}
]]>
        </example>
    </rule>

    <rule name="UnusedSuppression"
          since="3.0.0"
          message="Avoid unused suppressions such as '{0}'."
          class="PHPMD\Rule\UnusedSuppression"
          externalInfoUrl="https://phpmd.org/rules/unusedcode.html#unusedsuppression">
        <description>
Detects SuppressWarnings attributes that no longer suppress any warning, for
example because the code was fixed, or the rule is not part of the analysis.
Suppress this rule to keep a suppression that is knowingly unused. Doc comment
annotations are not reported.
        </description>
        <priority>3</priority>
        <example>
<![CDATA[
use PHPMD\Attribute\SuppressWarnings;
use PHPMD\Rule\UnusedLocalVariable;

class Foo
{
    #[SuppressWarnings(UnusedLocalVariable::class)] // unused
    public function bar()
    {
        return 42;
    }
}
]]>
        </example>
    </rule>

</ruleset>

=== phpmd/phpmd/tests/resources/files/rulesets/set2.xml
<?xml version="1.0" encoding="UTF-8"?>

<ruleset name="Second Test RuleSet"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>Second description...</description>
    
    <rule name="RuleOneInSecondRuleSet"
          since="0.1"
          message="Test message"
          class="PHPMD\Stubs\RuleStub"
          externalInfoUrl="https://phpmd.org/">
        <description>...</description>
        <priority>1</priority>
        <properties />
        <example>testCreateRuleWithExpectedMultipleExamplesOne</example>
        <example>testCreateRuleWithExpectedMultipleExamplesTwo</example>
    </rule>
    <rule name="RuleTwoInSecondRuleSet"
          since="0.1"
          message="Test message"
          class="PHPMD\Stubs\RuleStub"
          externalInfoUrl="https://phpmd.org/">
        <description>...</description>
        <priority>5</priority>
        <properties />
    </rule>
</ruleset>

=== phpmd/phpmd/tests/resources/files/rulesets/set1.xml
<?xml version="1.0" encoding="UTF-8"?>

<ruleset name="First Test RuleSet"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>First description...</description>
    <rule name="RuleOneInFirstRuleSet"
          since="0.1"
          message="Test message"
          class="PHPMD\Stubs\RuleStub"
          externalInfoUrl="https://phpmd.org/">
        <description>...</description>
        <priority>3</priority>
        <properties />
        <example>testCreateRuleWithExpectedExample</example>
    </rule>
    <rule name="RuleTwoInFirstRuleSet"
          since="0.1"
          message="Test message"
          class="PHPMD\Stubs\RuleStub"
          externalInfoUrl="https://phpmd.org/">
        <description>...</description>
        <priority>1</priority>
        <properties />
    </rule>
</ruleset>
