=== phpmd/phpmd/public/resources/web/xml/ruleset_xml_schema_1.0.0.xsd
<?xml version="1.0"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns="https://phpmd.org/xml/ruleset/1.0.0"
        targetNamespace="https://phpmd.org/xml/ruleset/1.0.0"
        elementFormDefault="qualified">

    <xs:element name="ruleset">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="format" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache-strategy" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="baseline-file" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="bootstrap" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="cache" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="minimum-priority" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="maximum-priority" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="threads" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="paths" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="exclude-pattern" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="include-pattern" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="suffixes" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="rule" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="php-includepath" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="php-includepath" type="xs:string">
    </xs:element>

    <xs:element name="description" type="xs:string">
    </xs:element>

    <xs:element name="include-pattern" type="xs:string">
    </xs:element>

    <xs:element name="exclude-pattern" type="xs:string">
    </xs:element>

    <xs:element name="rule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="description" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="priority" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="properties" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="exclude" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element ref="example" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:ID" use="optional"/>
            <xs:attribute name="file" type="xs:string" use="optional"/>
            <xs:attribute name="since" type="xs:string" use="optional"/>
            <xs:attribute name="ref" type="xs:string" use="optional"/>
            <xs:attribute name="message" type="xs:string" use="optional"/>
            <xs:attribute name="externalInfoUrl" type="xs:string" use="optional"/>
            <xs:attribute name="class" type="xs:NMTOKEN" use="optional"/>
            <xs:attribute name="dfa" type="xs:boolean" use="optional"/>  <!-- rule uses dataflow analysis -->
            <xs:attribute name="typeResolution" type="xs:boolean" default="false" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="example" type="xs:string"/>

    <!-- Default priority is the lowest -->
    <xs:element name="priority" type="xs:int" default="5"/>

    <xs:element name="properties">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="property" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="property">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="value" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
            <xs:attribute name="value" type="xs:string" use="optional"/>
            <xs:attribute name="description" type="xs:string" use="optional"/>
            <xs:attribute name="pluginname" type="xs:NMTOKEN" use="optional"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="value" type="xs:string">
    </xs:element>

    <xs:element name="exclude">
        <xs:complexType>
            <xs:attribute name="name" type="xs:NMTOKEN" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== phpmd/phpmd/rulesets/cleancode.xml
<?xml version="1.0"?>

<ruleset name="Clean Code Rules"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>
The Clean Code ruleset contains rules that enforce a clean code base. This includes rules from SOLID and object calisthenics.
    </description>

    <rule name="BooleanArgumentFlag"
          since="1.4.0"
          message="The method {0} has a boolean flag argument {1}, which is a certain sign of a Single Responsibility Principle violation."
          class="PHPMD\Rule\CleanCode\BooleanArgumentFlag"
          externalInfoUrl="https://phpmd.org/rules/cleancode.html#booleanargumentflag">
        <description>
            <![CDATA[
A boolean flag argument is a reliable indicator for a violation of
the Single Responsibility Principle (SRP). You can fix this problem
by extracting the logic in the boolean flag into its own class
or method.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="exceptions" description="Comma-separated class name list of exceptions" value=""/>
            <property name="ignorepattern" description="Ignore methods matching this regex. Example: /^(__construct|get.*Filtered)$/" value=""/>
        </properties>
        <example>
            <![CDATA[
class Foo {
    public function bar($flag = true) {
    }
}
            ]]>
        </example>
    </rule>

    <rule name="ElseExpression"
          since="1.4.0"
          message="The method {0} uses an else expression. Else clauses are basically not necessary and you can simplify the code by not using them."
          class="PHPMD\Rule\CleanCode\ElseExpression"
          externalInfoUrl="https://phpmd.org/rules/cleancode.html#elseexpression">
        <description>
            <![CDATA[
An if expression with an else branch is basically not necessary. You can rewrite the
conditions in a way that the else clause is not necessary and the code becomes simpler
to read.  To achieve this, use early return statements, though you may
need to split the code it several smaller methods. For very simple assignments
you could also use the ternary operations.
            ]]>
        </description>
        <priority>1</priority>
        <properties/>
        <example>
            <![CDATA[
class Foo
{
    public function bar($flag)
    {
        if ($flag) {
            // one branch
        } else {
            // another branch
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="IfStatementAssignment"
          since="2.7.0"
          message="Avoid assigning values to variables in if clauses and the like (line '{0}', column '{1}')."
          class="PHPMD\Rule\CleanCode\IfStatementAssignment"
          externalInfoUrl="http://phpmd.org/rules/cleancode.html#ifstatementassignment">
        <description>
            <![CDATA[
Assignments in if clauses and the like are considered a code smell.
Assignments in PHP return the right operand as their result.
In many cases, this is an expected behavior, but can lead
to many difficult to spot bugs, especially when the right
operand could result in zero, null or an empty string and the like.
            ]]>
        </description>
        <priority>1</priority>
        <properties/>
        <example>
            <![CDATA[
class Foo
{
    public function bar($flag)
    {
        if ($foo = 'bar') { // possible typo
            // ...
        }
        if ($baz = 0) { // always false
            // ...
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="StaticAccess"
          since="1.4.0"
          message="Avoid using static access to class '{0}' in method '{1}'."
          class="PHPMD\Rule\CleanCode\StaticAccess"
          externalInfoUrl="https://phpmd.org/rules/cleancode.html#staticaccess">
        <description>
            <![CDATA[
Static access causes unexchangeable dependencies to other classes and leads to hard to test code. Avoid
using static access at all costs and instead inject dependencies through the constructor. The only
case when static access is acceptable is when used for factory methods.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="exceptions" description="Comma-separated class name list of exceptions" value=""/>
            <property name="ignorepattern" description="Ignore methods matching this regex. Example: /^create/i" value=""/>
        </properties>
        <example>
            <![CDATA[
class Foo
{
    public function bar()
    {
        Bar::baz();
    }
}
            ]]>
        </example>
    </rule>

    <rule name="IfStatementWithoutLogic"
          since="2.9.0"
          message="Unneeded if statement on line '{0}' in method '{1}'."
          class="PHPMD\Rule\CleanCode\IfStatementWithoutLogic"
          externalInfoUrl="https://phpmd.org/rules/cleancode.html#ifstatementwithoutlogic">
        <description>
            <![CDATA[
Having if conditions without any logic should be avoided. It usually tells us,
that we are dealing with development code fragment, debug data, etc.
            ]]>
        </description>
        <priority>1</priority>
        <properties />
        <example>
            <![CDATA[
    public function bar()
    {
        if (true) { // always true
            // ...
        }
        if (1 !== 1) { // always false
            // ...
        }
    }
}
            ]]>
        </example>
    </rule>

    <rule name="DuplicatedArrayKey"
          message="Duplicated array key {0}, first declared at line {1}."
          class="PHPMD\Rule\CleanCode\DuplicatedArrayKey"
          externalInfoUrl="http://phpmd.org/rules/cleancode.html#duplicatedarraykey">
        <description>
            <![CDATA[
Defining another value for the same key in an array literal overrides the previous key/value,
which makes it effectively an unused code. If it's known from the beginning that the key
will have different value, there is usually no point in defining first one.
            ]]>
        </description>
        <priority>2</priority>
        <example>
            <![CDATA[
function createArray() {
    return [
        'non-associative 0element', // not applied
        0 => 'associative 0-element', // applied
        false => 'associative 0-element', // applied
        'foo' => 'bar', // not applied
        "foo" => 'baz', // applied
    ];
}
            ]]>
        </example>
    </rule>

    <rule name="ErrorControlOperator"
          message="Remove error control operator '@' on line {0}."
          class="PHPMD\Rule\CleanCode\ErrorControlOperator"
          externalInfoUrl="http://phpmd.org/rules/cleancode.html#errorcontroloperator">
        <description>
            <![CDATA[
Error suppression should be avoided if possible as it doesn't just suppress the error, that
you are trying to stop, but will also suppress errors that you didn't predict would ever occur.
Consider changing error_reporting() level and/or setting up your own error handler.
            ]]>
        </description>
        <priority>1</priority>
        <example>
            <![CDATA[
function foo($filePath) {
    $file = @fopen($filPath); // hides exceptions
    $key = @$array[$notExistingKey]; // assigns null to $key
}
            ]]>
        </example>
    </rule>

    <rule name="MissingImport"
          since="2.7.0"
          message="Missing class import via use statement (line '{0}', column '{1}')."
          class="PHPMD\Rule\CleanCode\MissingImport"
          externalInfoUrl="http://phpmd.org/rules/cleancode.html#MissingImport">
        <description>
            <![CDATA[
Importing all external classes in a file through use statements makes them clearly visible.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="ignore-global" value="false" description="Ignore classes in the global namespace" />
        </properties>
        <example>
            <![CDATA[
function make() {
    return new \stdClass();
}
            ]]>
        </example>
    </rule>

    <rule name="UndefinedVariable"
          since="2.8.0"
          message="Avoid using undefined variables such as '{0}' which will lead to PHP notices."
          class="PHPMD\Rule\CleanCode\UndefinedVariable"
          externalInfoUrl="https://phpmd.org/rules/cleancode.html#undefinedvariable">
        <description>
            Detects when a variable is used that has not been defined before.
        </description>
        <priority>3</priority>
        <example>
            <![CDATA[
class Foo
{
    private function bar()
    {
        // $message is undefined
        echo $message;
    }
}
]]>
        </example>
    </rule>

</ruleset>

=== phpmd/phpmd/src/main/resources/rulesets/controversial.xml
<?xml version="1.0"?>

<ruleset name="Controversial Rules"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>
This ruleset contains a collection of controversial rules.
    </description>

    <rule name="Superglobals"
          since="0.2"
          message = "{0} accesses the super-global variable {1}."
          class="PHPMD\Rule\Controversial\Superglobals"
          externalInfoUrl="https://phpmd.org/rules/naming.html#superglobals">
        <description>
            <![CDATA[
Accessing a super-global variable directly is considered a bad practice.
These variables should be encapsulated in objects that are provided by a framework, for instance.
            ]]>
        </description>
        <priority>1</priority>
        <properties />
        <example>
            <![CDATA[
class Foo {
    public function bar() {
        $name = $_POST['foo'];
    }
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCaseClassName"
          since="0.2"
          message = "The class {0} is not named in CamelCase."
          class="PHPMD\Rule\Controversial\CamelCaseClassName"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcaseclassname">
        <description>
            <![CDATA[
It is considered best practice to use the CamelCase notation to name classes.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="camelcase-abbreviations"
                      description="Name should be CamelCase including abbreviations."
                      value="false" />
        </properties>
        <example>
            <![CDATA[
class class_name {
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCaseNamespace"
          since="2.16"
          message = "The name {0} in namespace {1} is not named in CamelCase."
          class="PHPMD\Rule\Controversial\CamelCaseNamespace"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcasenamespace">
        <description>
            <![CDATA[
A rule to use CamelCase notation to name namespaces.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="camelcase-abbreviations"
                      description="Name should be CamelCase including abbreviations."
                      value="false" />
            <property name="exceptions"
                      description="Comma-separated class name list of exceptions"
                      value=""/>
        </properties>
        <example>
            <![CDATA[
use example\name_space;

class class_name {
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCasePropertyName"
          since="0.2"
          message = "The property {0} is not named in camelCase."
          class="PHPMD\Rule\Controversial\CamelCasePropertyName"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcasepropertyname">
        <description>
            <![CDATA[
It is considered best practice to use the camelCase notation to name attributes.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="allow-underscore"
                      description="Allow an optional, single underscore at the beginning."
                      value="false" />
            <property name="allow-underscore-test"
                      description="Is it allowed to have underscores in test method names."
                      value="false" />
            <property name="camelcase-abbreviations"
                      description="Name should be camelCase including abbreviations."
                      value="false" />
        </properties>
        <example>
            <![CDATA[
class ClassName {
    protected $property_name;
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCaseMethodName"
          since="0.2"
          message = "The method {0} is not named in camelCase."
          class="PHPMD\Rule\Controversial\CamelCaseMethodName"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcasemethodname">
        <description>
            <![CDATA[
It is considered best practice to use the camelCase notation to name methods.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="allow-underscore"
                      description="Allow an optional, single underscore at the beginning."
                      value="false" />
            <property name="allow-underscore-test"
                      description="Is it allowed to have underscores in test method names."
                      value="false" />
            <property name="camelcase-abbreviations"
                      description="Name should be camelCase including abbreviations."
                      value="false" />
        </properties>
        <example>
            <![CDATA[
class ClassName {
    public function get_name() {
    }
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCaseParameterName"
          since="0.2"
          message = "The parameter {0} is not named in camelCase."
          class="PHPMD\Rule\Controversial\CamelCaseParameterName"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcaseparametername">
        <description>
            <![CDATA[
It is considered best practice to use the camelCase notation to name parameters.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="allow-underscore"
                      description="Allow an optional, single underscore at the beginning."
                      value="false" />
            <property name="camelcase-abbreviations"
                      description="Name should be camelCase including abbreviations."
                      value="false" />
        </properties>
        <example>
            <![CDATA[
class ClassName {
    public function doSomething($user_name) {
    }
}
            ]]>
        </example>
    </rule>

    <rule name="CamelCaseVariableName"
          since="0.2"
          message = "The variable {0} is not named in camelCase."
          class="PHPMD\Rule\Controversial\CamelCaseVariableName"
          externalInfoUrl="https://phpmd.org/rules/naming.html#camelcasevariablename">
        <description>
            <![CDATA[
It is considered best practice to use the camelCase notation to name variables.
            ]]>
        </description>
        <priority>1</priority>
        <properties>
            <property name="allow-underscore"
                      description="Allow an optional, single underscore at the beginning."
                      value="false" />
            <property name="camelcase-abbreviations"
                      description="Name should be camelCase including abbreviations."
                      value="false" />
        </properties>
        <example>
            <![CDATA[
class ClassName {
    public function doSomething() {
        $data_module = new DataModule();
    }
}
            ]]>
        </example>
    </rule>
</ruleset>

=== phpmd/phpmd/tests/resources/files/rulesets/refset3.xml
<?xml version="1.0" encoding="UTF-8"?>

<ruleset name="Third Test RuleSet"
         xmlns="https://phpmd.org/xml/ruleset/1.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://phpmd.org/xml/ruleset/1.0.0 http://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd"
         xsi:noNamespaceSchemaLocation="https://phpmd.org/xml/ruleset_xml_schema_1.0.0.xsd">

    <description>First description...</description>

    <rule ref="rulesets/set1.xml/RuleTwoInFirstRuleSet">
        <description> description 42 </description>
        <priority>4</priority>
        <properties>
            <property name="foo" value="42" />
        </properties>
        <example><![CDATA[foreach ($foo as $bar) { echo $bar; }]]></example>
    </rule>
</ruleset>
